// Generated by Sideko (sideko.dev)
use crate::schemas::*;

pub struct DeleteApisApiIdRequest {
    pub api_id: String,
}

pub struct DeleteApisApiIdSchemasSchemaIdFilesFilePathRequest {
    pub api_id: String,
    pub schema_id: String,
    pub file_path: String,
}

pub struct DeleteApisApiIdVersionsVersionIdRequest {
    pub api_id: String,
    pub version_id: String,
}

pub struct DeleteCollectionsCollectionIdRequest {
    pub collection_id: String,
}

pub struct DeleteCollectionsCollectionIdFoldersFolderIdRequest {
    pub collection_id: String,
    pub folder_id: String,
}

pub struct DeleteCollectionsCollectionIdRequestsRequestIdRequest {
    pub collection_id: String,
    pub request_id: String,
}

pub struct DeleteCollectionsCollectionIdResponsesResponseIdRequest {
    pub collection_id: String,
    pub response_id: String,
}

pub struct DeleteEnvironmentsEnvironmentIdRequest {
    pub environment_id: String,
}

pub struct DeleteMocksMockIdRequest {
    pub mock_id: String,
}

pub struct DeleteMocksMockIdServerResponsesServerResponseIdRequest {
    pub mock_id: String,
    pub server_response_id: String,
}

pub struct DeleteMocksMockIdUnpublishRequest {
    pub mock_id: String,
}

pub struct DeleteMonitorsMonitorIdRequest {
    pub monitor_id: String,
}

pub struct DeleteNetworkPrivateElementTypeElementIdRequest {
    pub element_type: String,
    pub element_id: String,
}

pub struct DeleteScimV2GroupsGroupIdRequest {
    pub group_id: String,
}

pub struct DeleteWorkspacesWorkspaceIdRequest {
    pub workspace_id: String,
}

pub struct GetApisRequest {
    pub workspace_id: String,
    pub created_by: Option<i64>,
    pub cursor: Option<String>,
    pub description: Option<String>,
    pub limit: Option<i64>,
}

pub struct GetApisApiIdRequest {
    pub api_id: String,
    pub include: Option<Vec<String>>,
}

pub struct GetApisApiIdCollectionsCollectionIdRequest {
    pub api_id: String,
    pub collection_id: String,
    pub version_id: Option<String>,
}

pub struct GetApisApiIdSchemasSchemaIdRequest {
    pub api_id: String,
    pub schema_id: String,
    pub bundled: Option<bool>,
    pub version_id: Option<String>,
}

pub struct GetApisApiIdSchemasSchemaIdFilesRequest {
    pub api_id: String,
    pub schema_id: String,
    pub cursor: Option<String>,
    pub limit: Option<i64>,
    pub version_id: Option<String>,
}

pub struct GetApisApiIdSchemasSchemaIdFilesFilePathRequest {
    pub api_id: String,
    pub schema_id: String,
    pub file_path: String,
    pub version_id: Option<String>,
}

pub struct GetApisApiIdTagsRequest {
    pub api_id: String,
}

pub struct GetApisApiIdTasksTaskIdRequest {
    pub api_id: String,
    pub task_id: String,
}

pub struct GetApisApiIdVersionsRequest {
    pub api_id: String,
    pub cursor: Option<String>,
    pub limit: Option<i64>,
}

pub struct GetApisApiIdVersionsVersionIdRequest {
    pub api_id: String,
    pub version_id: String,
}

pub struct GetAuditLogsRequest {
    pub cursor: Option<String>,
    pub limit: Option<i64>,
    pub order_by: Option<String>,
    pub since: Option<String>,
    pub until: Option<String>,
}

pub struct GetCollectionsRequest {
    pub name: Option<String>,
    pub workspace_id: Option<String>,
}

pub struct GetCollectionsCollectionIdRequest {
    pub collection_id: String,
    pub access_key: Option<String>,
}

pub struct GetCollectionsCollectionIdFoldersFolderIdRequest {
    pub collection_id: String,
    pub folder_id: String,
    pub ids: Option<bool>,
    pub populate: Option<bool>,
    pub uid: Option<bool>,
}

pub struct GetCollectionsCollectionIdRequestsRequestIdRequest {
    pub collection_id: String,
    pub request_id: String,
    pub ids: Option<String>,
    pub populate: Option<bool>,
    pub uid: Option<bool>,
}

pub struct GetCollectionsCollectionIdResponsesResponseIdRequest {
    pub collection_id: String,
    pub response_id: String,
    pub ids: Option<bool>,
    pub populate: Option<bool>,
    pub uid: Option<bool>,
}

pub struct GetCollectionsCollectionIdTagsRequest {
    pub collection_id: String,
}

pub struct GetCollectionsCollectionIdTransformationsRequest {
    pub collection_id: String,
}

pub struct GetDetectedSecretsSecretIdLocationsRequest {
    pub secret_id: String,
    pub workspace_id: String,
    pub cursor: Option<String>,
    pub limit: Option<i64>,
}

pub struct GetEnvironmentsRequest {
    pub workspace_id: Option<String>,
}

pub struct GetEnvironmentsEnvironmentIdRequest {
    pub environment_id: String,
}

pub struct GetMocksRequest {
    pub team_id: Option<String>,
    pub workspace: Option<String>,
}

pub struct GetMocksMockIdRequest {
    pub mock_id: String,
}

pub struct GetMocksMockIdCallLogsRequest {
    pub mock_id: String,
    pub cursor: Option<String>,
    pub direction: Option<String>,
    pub include: Option<String>,
    pub limit: Option<f32>,
    pub request_method: Option<String>,
    pub request_path: Option<String>,
    pub response_status_code: Option<f32>,
    pub response_type: Option<String>,
    pub since: Option<String>,
    pub sort: Option<String>,
    pub until: Option<String>,
}

pub struct GetMocksMockIdServerResponsesRequest {
    pub mock_id: String,
}

pub struct GetMocksMockIdServerResponsesServerResponseIdRequest {
    pub mock_id: String,
    pub server_response_id: String,
}

pub struct GetMonitorsRequest {
    pub workspace: Option<String>,
}

pub struct GetMonitorsMonitorIdRequest {
    pub monitor_id: String,
}

pub struct GetNetworkPrivateRequest {
    pub added_by: Option<i64>,
    pub created_by: Option<i64>,
    pub description: Option<String>,
    pub direction: Option<String>,
    pub limit: Option<i64>,
    pub name: Option<String>,
    pub offset: Option<i64>,
    pub parent_folder_id: Option<i64>,
    pub since: Option<String>,
    pub sort: Option<String>,
    pub summary: Option<String>,
    pub type_field: Option<String>,
    pub until: Option<String>,
}

pub struct GetNetworkPrivateNetworkEntityRequestAllRequest {
    pub direction: Option<String>,
    pub limit: Option<i64>,
    pub name: Option<String>,
    pub offset: Option<i64>,
    pub requested_by: Option<i64>,
    pub since: Option<String>,
    pub sort: Option<String>,
    pub status: Option<String>,
    pub type_field: Option<String>,
    pub until: Option<String>,
}

pub struct GetScimV2GroupsRequest {
    pub count: Option<f32>,
    pub filter: Option<String>,
    pub start_index: Option<f32>,
}

pub struct GetScimV2GroupsGroupIdRequest {
    pub group_id: String,
}

pub struct GetScimV2UsersRequest {
    pub count: Option<f32>,
    pub filter: Option<String>,
    pub start_index: Option<f32>,
}

pub struct GetScimV2UsersUserIdRequest {
    pub user_id: String,
}

pub struct GetTagsSlugEntitiesRequest {
    pub slug: String,
    pub cursor: Option<String>,
    pub direction: Option<String>,
    pub entity_type: Option<String>,
    pub limit: Option<i64>,
}

pub struct GetWorkspacesRequest {
    pub type_field: Option<String>,
}

pub struct GetWorkspacesWorkspaceIdRequest {
    pub workspace_id: String,
}

pub struct GetWorkspacesWorkspaceIdGlobalVariablesRequest {
    pub workspace_id: String,
}

pub struct GetWorkspacesWorkspaceIdTagsRequest {
    pub workspace_id: String,
}

pub struct PatchCollectionsCollectionIdRequest {
    pub collection_id: String,
    pub data: PatchCollectionsCollectionIdBody,
}

pub struct PatchScimV2GroupsGroupIdRequest {
    pub group_id: String,
    pub data: PatchScimV2GroupsGroupIdBody,
}

pub struct PatchScimV2UsersUserIdRequest {
    pub user_id: String,
    pub data: PatchScimV2UsersUserIdBody,
}

pub struct PostApisRequest {
    pub workspace_id: String,
    pub data: PostApisBody,
}

pub struct PostApisApiIdCollectionsRequest {
    pub api_id: String,
    pub data: serde_json::Value,
}

pub struct PostApisApiIdSchemasRequest {
    pub api_id: String,
    pub data: PostApisApiIdSchemasBody,
}

pub struct PostApisApiIdVersionsRequest {
    pub api_id: String,
    pub data: serde_json::Value,
}

pub struct PostCollectionsRequest {
    pub workspace_id: Option<String>,
    pub data: PostCollectionsBody,
}

pub struct PostCollectionsForkCollectionIdRequest {
    pub collection_id: String,
    pub workspace: String,
    pub data: PostCollectionsForkCollectionIdBody,
}

pub struct PostCollectionsMergeRequest {
    pub data: PostCollectionsMergeBody,
}

pub struct PostCollectionsCollectionIdFoldersRequest {
    pub collection_id: String,
    pub data: PostCollectionsCollectionIdFoldersBody,
}

pub struct PostCollectionsCollectionIdRequestsRequest {
    pub collection_id: String,
    pub folder_id: Option<String>,
    pub data: PostCollectionsCollectionIdRequestsBody,
}

pub struct PostCollectionsCollectionIdResponsesRequest {
    pub collection_id: String,
    pub request_id: String,
    pub data: PostCollectionsCollectionIdResponsesBody,
}

pub struct PostDetectedSecretsQueriesRequest {
    pub cursor: Option<String>,
    pub include: Option<String>,
    pub limit: Option<i64>,
    pub data: PostDetectedSecretsQueriesBody,
}

pub struct PostEnvironmentsRequest {
    pub workspace_id: Option<String>,
    pub data: PostEnvironmentsBody,
}

pub struct PostImportOpenapiRequest {
    pub workspace_id: Option<String>,
    pub data: serde_json::Value,
}

pub struct PostMocksRequest {
    pub workspace_id: Option<String>,
    pub data: PostMocksBody,
}

pub struct PostMocksMockIdPublishRequest {
    pub mock_id: String,
}

pub struct PostMocksMockIdServerResponsesRequest {
    pub mock_id: String,
    pub data: PostMocksMockIdServerResponsesBody,
}

pub struct PostMonitorsRequest {
    pub workspace_id: Option<String>,
    pub data: PostMonitorsBody,
}

pub struct PostMonitorsMonitorIdRunRequest {
    pub monitor_id: String,
}

pub struct PostNetworkPrivateRequest {
    pub data: serde_json::Value,
}

pub struct PostScimV2GroupsRequest {
    pub data: PostScimV2GroupsBody,
}

pub struct PostScimV2UsersRequest {
    pub data: PostScimV2UsersBody,
}

pub struct PostSecurityApiValidationRequest {
    pub data: PostSecurityApiValidationBody,
}

pub struct PostWebhooksRequest {
    pub workspace_id: Option<String>,
    pub data: PostWebhooksBody,
}

pub struct PostWorkspacesRequest {
    pub data: PostWorkspacesBody,
}

pub struct PutApisApiIdRequest {
    pub api_id: String,
    pub data: PutApisApiIdBody,
}

pub struct PutApisApiIdCollectionsCollectionIdSyncWithSchemaTasksRequest {
    pub api_id: String,
    pub collection_id: String,
}

pub struct PutApisApiIdSchemasSchemaIdFilesFilePathRequest {
    pub api_id: String,
    pub schema_id: String,
    pub file_path: String,
    pub data: PutApisApiIdSchemasSchemaIdFilesFilePathBody,
}

pub struct PutApisApiIdTagsRequest {
    pub api_id: String,
    pub data: PutApisApiIdTagsBody,
}

pub struct PutApisApiIdVersionsVersionIdRequest {
    pub api_id: String,
    pub version_id: String,
    pub data: PutApisApiIdVersionsVersionIdBody,
}

pub struct PutCollectionsCollectionIdRequest {
    pub collection_id: String,
    pub data: PutCollectionsCollectionIdBody,
}

pub struct PutCollectionsCollectionIdFoldersFolderIdRequest {
    pub collection_id: String,
    pub folder_id: String,
    pub data: PutCollectionsCollectionIdFoldersFolderIdBody,
}

pub struct PutCollectionsCollectionIdRequestsRequestIdRequest {
    pub collection_id: String,
    pub request_id: String,
    pub data: PutCollectionsCollectionIdRequestsRequestIdBody,
}

pub struct PutCollectionsCollectionIdResponsesResponseIdRequest {
    pub collection_id: String,
    pub response_id: String,
    pub data: PutCollectionsCollectionIdResponsesResponseIdBody,
}

pub struct PutCollectionsCollectionIdTagsRequest {
    pub collection_id: String,
    pub data: PutCollectionsCollectionIdTagsBody,
}

pub struct PutDetectedSecretsSecretIdRequest {
    pub secret_id: String,
    pub data: PutDetectedSecretsSecretIdBody,
}

pub struct PutEnvironmentsEnvironmentIdRequest {
    pub environment_id: String,
    pub data: PutEnvironmentsEnvironmentIdBody,
}

pub struct PutMocksMockIdRequest {
    pub mock_id: String,
    pub data: PutMocksMockIdBody,
}

pub struct PutMocksMockIdServerResponsesServerResponseIdRequest {
    pub mock_id: String,
    pub server_response_id: String,
    pub data: PutMocksMockIdServerResponsesServerResponseIdBody,
}

pub struct PutMonitorsMonitorIdRequest {
    pub monitor_id: String,
    pub data: PutMonitorsMonitorIdBody,
}

pub struct PutNetworkPrivateNetworkEntityRequestRequestIdRequest {
    pub request_id: i64,
    pub data: PutNetworkPrivateNetworkEntityRequestRequestIdBody,
}

pub struct PutNetworkPrivateElementTypeElementIdRequest {
    pub element_type: String,
    pub element_id: String,
    pub data: serde_json::Value,
}

pub struct PutScimV2UsersUserIdRequest {
    pub user_id: String,
    pub data: PutScimV2UsersUserIdBody,
}

pub struct PutWorkspacesWorkspaceIdRequest {
    pub workspace_id: String,
    pub data: PutWorkspacesWorkspaceIdBody,
}

pub struct PutWorkspacesWorkspaceIdGlobalVariablesRequest {
    pub workspace_id: String,
    pub data: PutWorkspacesWorkspaceIdGlobalVariablesBody,
}

pub struct PutWorkspacesWorkspaceIdTagsRequest {
    pub workspace_id: String,
    pub data: PutWorkspacesWorkspaceIdTagsBody,
}
